language: python
python: 3.6
env:
  - TOX_ENV=py36
install:
  - pip install tox
  - pip install coverage
  - pip install python-coveralls
script:
  - bash build.sh
after_success:
  - coveralls
notifications:
  email: false